name: compositor
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: amir <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  args: ^1.6.0
  path: ^1.6.0
  googleapis_auth: ^0.2.11+1
  http: ^0.12.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
